[workspace]
name = "zkvm_aggregation_programs"
version = "0.1.0"
edition = "2021"
resolver = "2"
members = ["sp1", "risc0"]

[patch.crates-io]
# Adding RISC Zero keccak precompile support
tiny-keccak = { git = "https://github.com/risc0/tiny-keccak", tag = "tiny-keccak/v2.0.2-risczero.0" }
