aligned_service_manager_address: "0x1613beB3B2C4f22Ee086B2b38C1476A3cE7f78E8"
proof_aggregation_service_address: "0xFD471836031dc5108809D173A067e8486B9047A3"
eth_rpc_url: "http://localhost:8545"
eth_ws_url: "ws://localhost:8546"
max_proofs_in_queue: 1000
last_aggregated_block_filepath: config-files/proof-aggregator.last_aggregated_block.json

ecdsa:
  private_key_store_path: "config-files/anvil.proof-aggregator.ecdsa.key.json"
  private_key_store_password: ""
